In [149]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
sns.set()

#!pip install mlxtend 
# 연관분석을 위한 패키지 인듯.
#from mlxtend.preprocessing import TransactionEncoder
#from mlxtend.frequent_patterns import apriori

In [150]:
df = pd.read_csv("실적.csv", encoding='cp949')
df

,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액
0,2019-01-01 6:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900.00,2099000.0
1,2019-01-01 6:00,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900.00,4371000.0
2,2019-01-01 6:20,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900.00,3262000.0
3,2019-01-01 6:20,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900.00,6955000.0
4,2019-01-01 6:40,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900.00,6672000.0
...,...,...,...,...,...,...,...,...
38304,2020-01-01 0:20,20.0,100073,200196,삼성화재 행복한파트너 주택화재보험(1912),무형,-,NaN
38305,2020-01-01 0:40,20.0,100073,200196,삼성화재 행복한파트너 주택화재보험(1912),무형,-,NaN
38306,2020-01-01 1:00,20.0,100073,200196,삼성화재 행복한파트너 주택화재보험(1912),무형,-,NaN
38307,2020-01-01 1:20,20.0,100490,201478,더케이 예다함 상조서비스(티포트),무형,-,NaN
38308,2020-01-01 1:40,17.0,100490,201478,더케이 예다함 상조서비스(티포트),무형,-,NaN

In [151]:
df.isnull().sum() # null 생각 보다 많았구나? 노출분은 그렇다 처도 취급액의 null은 필요 없는 거잖아?

방송일시         0
노출(분)    16784
마더코드         0
상품코드         0
상품명          0
상품군          0
판매단가         0
취급액        937
dtype: int64

###### 취급액에 있는 null 값 제거

In [188]:
df.dropna(subset=['취급액'], inplace=True)

In [153]:
df.isnull().sum() # 취급액의 NAN 값 삭제. 판 금액이 없는 거니깐 필요 없을 듯

방송일시         0
노출(분)    16784
마더코드         0
상품코드         0
상품명          0
상품군          0
판매단가         0
취급액          0
dtype: int64

In [154]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 37372 entries, 0 to 38303
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   방송일시    37372 non-null  object
 1   노출(분)   20588 non-null  float64
 2   마더코드    37372 non-null  int64
 3   상품코드    37372 non-null  int64
 4   상품명     37372 non-null  object
 5   상품군     37372 non-null  object
 6   판매단가    37372 non-null  object
 7   취급액     37372 non-null  float64
dtypes: float64(2), int64(2), object(4)
memory usage: 2.6+ MB

In [155]:
df.corr()

          노출(분)      마더코드      상품코드       취급액
노출(분)  1.000000  0.077447  0.072351  0.144344
마더코드   0.077447  1.000000  0.978878 -0.029025
상품코드   0.072351  0.978878  1.000000 -0.015692
취급액    0.144344 -0.029025 -0.015692  1.000000

In [156]:
df['방송일시'] = pd.to_datetime(df['방송일시'])

In [157]:
df['월'] = df['방송일시'].dt.month

In [158]:
df['일'] = df['방송일시'].dt.day

In [159]:
df['요일'] = df['방송일시'].dt.dayofweek

In [160]:
df

,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액,월,일,요일
0,2019-01-01 06:00:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900.00,2099000.0,1,1,1
1,2019-01-01 06:00:00,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900.00,4371000.0,1,1,1
2,2019-01-01 06:20:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900.00,3262000.0,1,1,1
3,2019-01-01 06:20:00,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900.00,6955000.0,1,1,1
4,2019-01-01 06:40:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900.00,6672000.0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...
38299,2019-12-31 23:40:00,NaN,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000.00,10157000.0,12,31,1
38300,2020-01-01 00:00:00,20.0,100448,201383,무이자쿠첸압력밥솥 10인용,주방,178000.00,50929000.0,1,1,2
38301,2020-01-01 00:00:00,NaN,100448,201390,일시불쿠첸압력밥솥 10인용,주방,168000.00,104392000.0,1,1,2
38302,2020-01-01 00:00:00,NaN,100448,201384,무이자쿠첸압력밥솥 6인용,주방,158000.00,13765000.0,1,1,2
38303,2020-01-01 00:00:00,NaN,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000.00,46608000.0,1,1,2

#### 화요일 1

In [161]:
df['판매단가']=df['판매단가'].astype(float)

In [162]:
df['수량'] = df['취급액']/df['판매단가']
df.dtypes

방송일시     datetime64[ns]
노출(분)           float64
마더코드              int64
상품코드              int64
상품명              object
상품군              object
판매단가            float64
취급액             float64
월                 int64
일                 int64
요일                int64
수량              float64
dtype: object

In [163]:
df

,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액,월,일,요일,수량
0,2019-01-01 06:00:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900.0,2099000.0,1,1,1,52.606516
1,2019-01-01 06:00:00,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900.0,4371000.0,1,1,1,109.548872
2,2019-01-01 06:20:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900.0,3262000.0,1,1,1,81.754386
3,2019-01-01 06:20:00,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900.0,6955000.0,1,1,1,174.310777
4,2019-01-01 06:40:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900.0,6672000.0,1,1,1,167.218045
...,...,...,...,...,...,...,...,...,...,...,...,...
38299,2019-12-31 23:40:00,NaN,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000.0,10157000.0,12,31,1,68.628378
38300,2020-01-01 00:00:00,20.0,100448,201383,무이자쿠첸압력밥솥 10인용,주방,178000.0,50929000.0,1,1,2,286.117978
38301,2020-01-01 00:00:00,NaN,100448,201390,일시불쿠첸압력밥솥 10인용,주방,168000.0,104392000.0,1,1,2,621.380952
38302,2020-01-01 00:00:00,NaN,100448,201384,무이자쿠첸압력밥솥 6인용,주방,158000.0,13765000.0,1,1,2,87.120253
38303,2020-01-01 00:00:00,NaN,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000.0,46608000.0,1,1,2,314.918919

In [164]:
df['의류'] = np.where(df['상품군'] == '의류', 1, 0)

In [165]:
df

,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액,월,일,요일,수량,의류
0,2019-01-01 06:00:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900.0,2099000.0,1,1,1,52.606516,1
1,2019-01-01 06:00:00,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900.0,4371000.0,1,1,1,109.548872,1
2,2019-01-01 06:20:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900.0,3262000.0,1,1,1,81.754386,1
3,2019-01-01 06:20:00,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900.0,6955000.0,1,1,1,174.310777,1
4,2019-01-01 06:40:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900.0,6672000.0,1,1,1,167.218045,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
38299,2019-12-31 23:40:00,NaN,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000.0,10157000.0,12,31,1,68.628378,0
38300,2020-01-01 00:00:00,20.0,100448,201383,무이자쿠첸압력밥솥 10인용,주방,178000.0,50929000.0,1,1,2,286.117978,0
38301,2020-01-01 00:00:00,NaN,100448,201390,일시불쿠첸압력밥솥 10인용,주방,168000.0,104392000.0,1,1,2,621.380952,0
38302,2020-01-01 00:00:00,NaN,100448,201384,무이자쿠첸압력밥솥 6인용,주방,158000.0,13765000.0,1,1,2,87.120253,0
38303,2020-01-01 00:00:00,NaN,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000.0,46608000.0,1,1,2,314.918919,0

In [166]:
df['주방'] = np.where(df['상품군']=='주방', 1 ,0)

In [167]:
df

,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액,월,일,요일,수량,의류,주방
0,2019-01-01 06:00:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900.0,2099000.0,1,1,1,52.606516,1,0
1,2019-01-01 06:00:00,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900.0,4371000.0,1,1,1,109.548872,1,0
2,2019-01-01 06:20:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900.0,3262000.0,1,1,1,81.754386,1,0
3,2019-01-01 06:20:00,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900.0,6955000.0,1,1,1,174.310777,1,0
4,2019-01-01 06:40:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900.0,6672000.0,1,1,1,167.218045,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38299,2019-12-31 23:40:00,NaN,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000.0,10157000.0,12,31,1,68.628378,0,1
38300,2020-01-01 00:00:00,20.0,100448,201383,무이자쿠첸압력밥솥 10인용,주방,178000.0,50929000.0,1,1,2,286.117978,0,1
38301,2020-01-01 00:00:00,NaN,100448,201390,일시불쿠첸압력밥솥 10인용,주방,168000.0,104392000.0,1,1,2,621.380952,0,1
38302,2020-01-01 00:00:00,NaN,100448,201384,무이자쿠첸압력밥솥 6인용,주방,158000.0,13765000.0,1,1,2,87.120253,0,1
38303,2020-01-01 00:00:00,NaN,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000.0,46608000.0,1,1,2,314.918919,0,1

In [173]:
df['가구'] = np.where(df['상품군']=='가구', 1 ,0)

In [175]:
df['생활용품'] = np.where(df['상품군']=='생활용품', 1 ,0)

In [176]:
df['속옷'] = np.where(df['상품군']=='속옷', 1 ,0)

In [177]:
df['이미용'] = np.where(df['상품군']=='이미용', 1 ,0)

In [178]:
df['침구'] = np.where(df['상품군']=='침구', 1 ,0)

In [179]:
df['잡화'] = np.where(df['상품군']=='잡화', 1 ,0)

In [180]:
df['건강기능'] = np.where(df['상품군']=='건강기능', 1 ,0)

In [181]:
df['가전'] = np.where(df['상품군']=='가전', 1 ,0)

In [182]:
df['농수축'] = np.where(df['상품군']=='농수축', 1 ,0)

In [187]:
df.corr()

,노출(분),마더코드,상품코드,판매단가,취급액,월,일,요일,수량,의류,...,가전,농수축,무형,생활용품,속옷,이미용,잡화,침구,남성,여성
노출(분),1.000000,0.077447,0.072351,0.111478,0.144344,-0.125432,-0.031129,-0.007397,0.001736,-0.075145,...,0.007614,-0.073471,NaN,0.003855,0.017053,-0.009316,0.035914,0.010075,-0.019596,0.021533
마더코드,0.077447,1.000000,0.978878,-0.214696,-0.029025,-0.081033,0.019849,-0.036389,0.012167,-0.025360,...,-0.272431,0.050732,NaN,0.007025,0.096604,-0.054523,0.043733,-0.112625,-0.038808,-0.022382
상품코드,0.072351,0.978878,1.000000,-0.227098,-0.015692,-0.096014,0.015430,-0.036677,0.023000,-0.010843,...,-0.287225,0.057643,NaN,0.006295,0.101208,-0.046301,0.031806,-0.127481,-0.041176,-0.025824
판매단가,0.111478,-0.214696,-0.227098,1.000000,-0.248520,-0.054958,-0.069088,0.070303,-0.380783,-0.154869,...,0.728397,-0.196290,NaN,-0.111164,-0.182507,-0.108437,0.000689,-0.071881,-0.150375,-0.119605
취급액,0.144344,-0.029025,-0.015692,-0.248520,1.000000,0.073841,0.038166,0.055360,0.770111,0.044982,...,-0.156092,0.351700,NaN,-0.056086,0.071268,0.149999,-0.098988,-0.076373,0.078221,-0.058992
월,-0.125432,-0.081033,-0.096014,-0.054958,0.073841,1.000000,-0.000289,-0.019322,0.076983,-0.035282,...,-0.131632,0.035979,NaN,0.148201,-0.049911,0.071029,0.087817,0.028291,0.001044,-0.003550
일,-0.031129,0.019849,0.015430,-0.069088,0.038166,-0.000289,1.000000,0.010615,0.051452,0.024744,...,-0.060315,0.022079,NaN,0.011844,0.013365,0.006573,0.013491,0.012822,0.016881,0.016468
요일,-0.007397,-0.036389,-0.036677,0.070303,0.055360,-0.019322,0.010615,1.000000,0.016060,0.046921,...,0.084562,-0.036631,NaN,-0.005861,-0.014898,0.000507,-0.001830,-0.028290,0.048297,0.025252
수량,0.001736,0.012167,0.023000,-0.380783,0.770111,0.076983,0.051452,0.016060,1.000000,0.073961,...,-0.306462,0.543791,NaN,-0.084609,0.053188,0.226918,-0.048627,-0.046078,0.157215,0.002901
의류,-0.075145,-0.025360,-0.010843,-0.154869,0.044982,-0.035282,0.024744,0.046921,0.073961,1.000000,...,-0.165997,-0.123445,NaN,-0.104681,-0.124064,-0.068949,-0.123569,-0.048937,0.382623,0.338215
주방,0.099009,0.236522,0.236738,-0.199880,-0.061106,-0.060960,0.012608,-0.048229,-0.118811,-0.167931,...,-0.212167,-0.157779,NaN,-0.133797,-0.158571,-0.088126,-0.157938,-0.062548,-0.126239,-0.100764
가구,0.005729,-0.078610,-0.070264,0.140776,-0.145638,0.006032,-0.064243,-0.019255,-0.182273,-0.099404,...,-0.125588,-0.093394,NaN,-0.079199,-0.093863,-0.052165,-0.093488,-0.037024,-0.074725,-0.059645
건강기능,0.007822,0.039803,0.036446,-0.077285,0.026018,0.028114,0.037996,-0.015404,0.026009,-0.053267,...,-0.067298,-0.050047,NaN,-0.042440,-0.050298,-0.027953,-0.050097,-0.019840,-0.040042,-0.031962
가전,0.007614,-0.272431,-0.287225,0.728397,-0.156092,-0.131632,-0.060315,0.084562,-0.306462,-0.165997,...,1.000000,-0.155962,NaN,-0.132256,-0.156745,-0.087111,-0.156119,-0.061828,-0.124786,-0.099603
농수축,-0.073471,0.050732,0.057643,-0.196290,0.351700,0.035979,0.022079,-0.036631,0.543791,-0.123445,...,-0.155962,1.000000,NaN,-0.098353,-0.116564,-0.064781,-0.116098,-0.045979,-0.092797,-0.074070
무형,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
생활용품,0.003855,0.007025,0.006295,-0.111164,-0.056086,0.148201,0.011844,-0.005861,-0.084609,-0.104681,...,-0.132256,-0.098353,NaN,1.000000,-0.098847,-0.054934,-0.098452,-0.038990,-0.078692,-0.062812
속옷,0.017053,0.096604,0.101208,-0.182507,0.071268,-0.049911,0.013365,-0.014898,0.053188,-0.124064,...,-0.156745,-0.116564,NaN,-0.098847,1.000000,-0.065106,-0.116681,-0.046210,-0.048158,-0.019350
이미용,-0.009316,-0.054523,-0.046301,-0.108437,0.149999,0.071029,0.006573,0.000507,0.226918,-0.068949,...,-0.087111,-0.064781,NaN,-0.054934,-0.065106,1.000000,-0.064846,-0.025681,0.275719,-0.041371
잡화,0.035914,0.043733,0.031806,0.000689,-0.098988,0.087817,0.013491,-0.001830,-0.048627,-0.123569,...,-0.156119,-0.116098,NaN,-0.098452,-0.116681,-0.064846,1.000000,-0.046025,0.052181,0.145235
침구,0.010075,-0.112625,-0.127481,-0.071881,-0.076373,0.028291,0.012822,-0.028290,-0.046078,-0.048937,...,-0.061828,-0.045979,NaN,-0.038990,-0.046210,-0.025681,-0.046025,1.000000,-0.036788,-0.029364
남성,-0.019596,-0.038808,-0.041176,-0.150375,0.078221,0.001044,0.016881,0.048297,0.157215,0.382623,...,-0.124786,-0.092797,NaN,-0.078692,-0.048158,0.275719,0.052181,-0.036788,1.000000,-0.059264
여성,0.021533,-0.022382,-0.025824,-0.119605,-0.058992,-0.003550,0.016468,0.025252,0.002901,0.338215,...,-0.099603,-0.074070,NaN,-0.062812,-0.019350,-0.041371,0.145235,-0.029364,-0.059264,1.000000

In [172]:
df['남성'] = df['상품명'].str.contains('남성')
df['여성'] = df['상품명'].str.contains('여성')
df.to_csv("C:/Users/rmafu/Desktop/bigcon-master/mymy.csv")

In [203]:
# 정리된 데이터 읽어오기
mydata = pd.read_csv('mydata.csv', encoding='cp949')

In [193]:
mydata

,Unnamed: 0,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액,월,...,건강기능,가전,농수축,생활용품,속옷,이미용,잡화,침구,남성,여성
0,0,2019-01-01 6:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,2099000,1,...,0,0,0,0,0,0,0,0,1,0
1,1,2019-01-01 6:00,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900,4371000,1,...,0,0,0,0,0,0,0,0,0,0
2,2,2019-01-01 6:20,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,3262000,1,...,0,0,0,0,0,0,0,0,1,0
3,3,2019-01-01 6:20,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900,6955000,1,...,0,0,0,0,0,0,0,0,0,1
4,4,2019-01-01 6:40,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,6672000,1,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37367,38299,2019-12-31 23:40,NaN,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000,10157000,12,...,0,0,0,0,0,0,0,0,0,0
37368,38300,2020-01-01 0:00,20.0,100448,201383,무이자쿠첸압력밥솥 10인용,주방,178000,50929000,1,...,0,0,0,0,0,0,0,0,0,0
37369,38301,2020-01-01 0:00,NaN,100448,201390,일시불쿠첸압력밥솥 10인용,주방,168000,104392000,1,...,0,0,0,0,0,0,0,0,0,0
37370,38302,2020-01-01 0:00,NaN,100448,201384,무이자쿠첸압력밥솥 6인용,주방,158000,13765000,1,...,0,0,0,0,0,0,0,0,0,0
37371,38303,2020-01-01 0:00,NaN,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000,46608000,1,...,0,0,0,0,0,0,0,0,0,0

In [194]:
mydata.corr()

,Unnamed: 0,노출(분),마더코드,상품코드,판매단가,취급액,월,일,요일,수량,...,건강기능,가전,농수축,생활용품,속옷,이미용,잡화,침구,남성,여성
Unnamed: 0,1.000000,-0.127894,-0.080073,-0.095392,-0.059455,0.077449,0.995680,0.083051,-0.018565,0.081024,...,0.031041,-0.135176,0.038659,0.147118,-0.049177,0.070785,0.088895,0.030184,0.001377,-0.003313
노출(분),-0.127894,1.000000,0.077447,0.072351,0.111478,0.144344,-0.125432,-0.031129,-0.007397,0.001736,...,0.007822,0.007614,-0.073471,0.003855,0.017053,-0.009316,0.035914,0.010075,-0.019596,0.021533
마더코드,-0.080073,0.077447,1.000000,0.978878,-0.214696,-0.029025,-0.081033,0.019849,-0.036389,0.012167,...,0.039803,-0.272431,0.050732,0.007025,0.096604,-0.054523,0.043733,-0.112625,-0.038808,-0.022366
상품코드,-0.095392,0.072351,0.978878,1.000000,-0.227098,-0.015692,-0.096014,0.015430,-0.036677,0.023000,...,0.036446,-0.287225,0.057643,0.006295,0.101208,-0.046301,0.031806,-0.127481,-0.041176,-0.025808
판매단가,-0.059455,0.111478,-0.214696,-0.227098,1.000000,-0.248520,-0.054958,-0.069088,0.070303,-0.380783,...,-0.077285,0.728397,-0.196290,-0.111164,-0.182507,-0.108437,0.000689,-0.071881,-0.150375,-0.119563
취급액,0.077449,0.144344,-0.029025,-0.015692,-0.248520,1.000000,0.073841,0.038166,0.055360,0.770111,...,0.026018,-0.156092,0.351700,-0.056086,0.071268,0.149999,-0.098988,-0.076373,0.078221,-0.058897
월,0.995680,-0.125432,-0.081033,-0.096014,-0.054958,0.073841,1.000000,-0.000289,-0.019322,0.076983,...,0.028114,-0.131632,0.035979,0.148201,-0.049911,0.071029,0.087817,0.028291,0.001044,-0.003343
일,0.083051,-0.031129,0.019849,0.015430,-0.069088,0.038166,-0.000289,1.000000,0.010615,0.051452,...,0.037996,-0.060315,0.022079,0.011844,0.013365,0.006573,0.013491,0.012822,0.016881,0.016685
요일,-0.018565,-0.007397,-0.036389,-0.036677,0.070303,0.055360,-0.019322,0.010615,1.000000,0.016060,...,-0.015404,0.084562,-0.036631,-0.005861,-0.014898,0.000507,-0.001830,-0.028290,0.048297,0.025388
수량,0.081024,0.001736,0.012167,0.023000,-0.380783,0.770111,0.076983,0.051452,0.016060,1.000000,...,0.026009,-0.306462,0.543791,-0.084609,0.053188,0.226918,-0.048627,-0.046078,0.157215,0.002960
의류,-0.034002,-0.075145,-0.025360,-0.010843,-0.154869,0.044982,-0.035282,0.024744,0.046921,0.073961,...,-0.053267,-0.165997,-0.123445,-0.104681,-0.124064,-0.068949,-0.123569,-0.048937,0.382623,0.337955
주방,-0.059352,0.099009,0.236522,0.236738,-0.199880,-0.061106,-0.060960,0.012608,-0.048229,-0.118811,...,-0.068082,-0.212167,-0.157779,-0.133797,-0.158571,-0.088126,-0.157938,-0.062548,-0.126239,-0.100732
가구,0.000575,0.005729,-0.078610,-0.070264,0.140776,-0.145638,0.006032,-0.064243,-0.019255,-0.182273,...,-0.040300,-0.125588,-0.093394,-0.079199,-0.093863,-0.052165,-0.093488,-0.037024,-0.074725,-0.059627
건강기능,0.031041,0.007822,0.039803,0.036446,-0.077285,0.026018,0.028114,0.037996,-0.015404,0.026009,...,1.000000,-0.067298,-0.050047,-0.042440,-0.050298,-0.027953,-0.050097,-0.019840,-0.040042,-0.031952
가전,-0.135176,0.007614,-0.272431,-0.287225,0.728397,-0.156092,-0.131632,-0.060315,0.084562,-0.306462,...,-0.067298,1.000000,-0.155962,-0.132256,-0.156745,-0.087111,-0.156119,-0.061828,-0.124786,-0.099572
농수축,0.038659,-0.073471,0.050732,0.057643,-0.196290,0.351700,0.035979,0.022079,-0.036631,0.543791,...,-0.050047,-0.155962,1.000000,-0.098353,-0.116564,-0.064781,-0.116098,-0.045979,-0.092797,-0.074047
생활용품,0.147118,0.003855,0.007025,0.006295,-0.111164,-0.056086,0.148201,0.011844,-0.005861,-0.084609,...,-0.042440,-0.132256,-0.098353,1.000000,-0.098847,-0.054934,-0.098452,-0.038990,-0.078692,-0.062792
속옷,-0.049177,0.017053,0.096604,0.101208,-0.182507,0.071268,-0.049911,0.013365,-0.014898,0.053188,...,-0.050298,-0.156745,-0.116564,-0.098847,1.000000,-0.065106,-0.116681,-0.046210,-0.048158,-0.019311
이미용,0.070785,-0.009316,-0.054523,-0.046301,-0.108437,0.149999,0.071029,0.006573,0.000507,0.226918,...,-0.027953,-0.087111,-0.064781,-0.054934,-0.065106,1.000000,-0.064846,-0.025681,0.275719,-0.041359
잡화,0.088895,0.035914,0.043733,0.031806,0.000689,-0.098988,0.087817,0.013491,-0.001830,-0.048627,...,-0.050097,-0.156119,-0.116098,-0.098452,-0.116681,-0.064846,1.000000,-0.046025,0.052181,0.145320
침구,0.030184,0.010075,-0.112625,-0.127481,-0.071881,-0.076373,0.028291,0.012822,-0.028290,-0.046078,...,-0.019840,-0.061828,-0.045979,-0.038990,-0.046210,-0.025681,-0.046025,1.000000,-0.036788,-0.029355
남성,0.001377,-0.019596,-0.038808,-0.041176,-0.150375,0.078221,0.001044,0.016881,0.048297,0.157215,...,-0.040042,-0.124786,-0.092797,-0.078692,-0.048158,0.275719,0.052181,-0.036788,1.000000,-0.059246
여성,-0.003313,0.021533,-0.022366,-0.025808,-0.119563,-0.058897,-0.003343,0.016685,0.025388,0.002960,...,-0.031952,-0.099572,-0.074047,-0.062792,-0.019311,-0.041359,0.145320,-0.029355,-0.059246,1.000000

C:\Users\rmafu\.conda\envs\env_cpu\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\rmafu\.conda\envs\env_cpu\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\rmafu\.conda\envs\env_cpu\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

In [210]:
mydata.drop(['남성'], axis=1, inplace=True)

In [211]:
mydata.drop(['여성'], axis=1, inplace=True)

In [213]:
mydata['sex'] = mydata['상품명']

In [214]:
for i in range(len(mydata)):
    if set(mydata['sex'][i].split()) & {"남성"} :
        mydata['sex'][i] = "남성"
    elif set(mydata['sex'][i].split()) & {"여성"} :
        mydata['sex'][i] = "여성"
    else :
        mydata['sex'][i] = "무관"

C:\Users\rmafu\.conda\envs\env_cpu\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\rmafu\.conda\envs\env_cpu\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\rmafu\.conda\envs\env_cpu\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

In [215]:
mydata

,Unnamed: 0,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액,월,...,가구,건강기능,가전,농수축,생활용품,속옷,이미용,잡화,침구,sex
0,0,2019-01-01 6:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,2099000,1,...,0,0,0,0,0,0,0,0,0,남성
1,1,2019-01-01 6:00,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900,4371000,1,...,0,0,0,0,0,0,0,0,0,여성
2,2,2019-01-01 6:20,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,3262000,1,...,0,0,0,0,0,0,0,0,0,남성
3,3,2019-01-01 6:20,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900,6955000,1,...,0,0,0,0,0,0,0,0,0,여성
4,4,2019-01-01 6:40,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,6672000,1,...,0,0,0,0,0,0,0,0,0,남성
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37367,38299,2019-12-31 23:40,NaN,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000,10157000,12,...,0,0,0,0,0,0,0,0,0,무관
37368,38300,2020-01-01 0:00,20.0,100448,201383,무이자쿠첸압력밥솥 10인용,주방,178000,50929000,1,...,0,0,0,0,0,0,0,0,0,무관
37369,38301,2020-01-01 0:00,NaN,100448,201390,일시불쿠첸압력밥솥 10인용,주방,168000,104392000,1,...,0,0,0,0,0,0,0,0,0,무관
37370,38302,2020-01-01 0:00,NaN,100448,201384,무이자쿠첸압력밥솥 6인용,주방,158000,13765000,1,...,0,0,0,0,0,0,0,0,0,무관
37371,38303,2020-01-01 0:00,NaN,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000,46608000,1,...,0,0,0,0,0,0,0,0,0,무관

In [224]:
mydata['남성'] = np.where(mydata['sex']=='남성', 1 ,0)

In [225]:
mydata['여성'] = np.where(mydata['sex']=='여성', 1 ,0)

In [226]:
mydata['무관'] = np.where(mydata['sex']=='무관', 1 ,0)

In [227]:
mydata

,Unnamed: 0,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액,월,...,농수축,생활용품,속옷,이미용,잡화,침구,sex,무관,여성,남성
0,0,2019-01-01 6:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,2099000,1,...,0,0,0,0,0,0,남성,0,0,1
1,1,2019-01-01 6:00,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900,4371000,1,...,0,0,0,0,0,0,여성,0,1,0
2,2,2019-01-01 6:20,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,3262000,1,...,0,0,0,0,0,0,남성,0,0,1
3,3,2019-01-01 6:20,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900,6955000,1,...,0,0,0,0,0,0,여성,0,1,0
4,4,2019-01-01 6:40,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,6672000,1,...,0,0,0,0,0,0,남성,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37367,38299,2019-12-31 23:40,NaN,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000,10157000,12,...,0,0,0,0,0,0,무관,1,0,0
37368,38300,2020-01-01 0:00,20.0,100448,201383,무이자쿠첸압력밥솥 10인용,주방,178000,50929000,1,...,0,0,0,0,0,0,무관,1,0,0
37369,38301,2020-01-01 0:00,NaN,100448,201390,일시불쿠첸압력밥솥 10인용,주방,168000,104392000,1,...,0,0,0,0,0,0,무관,1,0,0
37370,38302,2020-01-01 0:00,NaN,100448,201384,무이자쿠첸압력밥솥 6인용,주방,158000,13765000,1,...,0,0,0,0,0,0,무관,1,0,0
37371,38303,2020-01-01 0:00,NaN,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000,46608000,1,...,0,0,0,0,0,0,무관,1,0,0

In [228]:
mydata.drop(['sex'],axis=1, inplace=True)

In [229]:
mydata

,Unnamed: 0,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액,월,...,가전,농수축,생활용품,속옷,이미용,잡화,침구,무관,여성,남성
0,0,2019-01-01 6:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,2099000,1,...,0,0,0,0,0,0,0,0,0,1
1,1,2019-01-01 6:00,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900,4371000,1,...,0,0,0,0,0,0,0,0,1,0
2,2,2019-01-01 6:20,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,3262000,1,...,0,0,0,0,0,0,0,0,0,1
3,3,2019-01-01 6:20,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900,6955000,1,...,0,0,0,0,0,0,0,0,1,0
4,4,2019-01-01 6:40,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,6672000,1,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37367,38299,2019-12-31 23:40,NaN,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000,10157000,12,...,0,0,0,0,0,0,0,1,0,0
37368,38300,2020-01-01 0:00,20.0,100448,201383,무이자쿠첸압력밥솥 10인용,주방,178000,50929000,1,...,0,0,0,0,0,0,0,1,0,0
37369,38301,2020-01-01 0:00,NaN,100448,201390,일시불쿠첸압력밥솥 10인용,주방,168000,104392000,1,...,0,0,0,0,0,0,0,1,0,0
37370,38302,2020-01-01 0:00,NaN,100448,201384,무이자쿠첸압력밥솥 6인용,주방,158000,13765000,1,...,0,0,0,0,0,0,0,1,0,0
37371,38303,2020-01-01 0:00,NaN,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000,46608000,1,...,0,0,0,0,0,0,0,1,0,0

In [230]:
mydata.corr()

,Unnamed: 0,노출(분),마더코드,상품코드,판매단가,취급액,월,일,요일,수량,...,가전,농수축,생활용품,속옷,이미용,잡화,침구,무관,여성,남성
Unnamed: 0,1.000000,-0.127894,-0.080073,-0.095392,-0.059455,0.077449,0.995680,0.083051,-0.018565,0.081024,...,-0.135176,0.038659,0.147118,-0.049177,0.070785,0.088895,0.030184,-0.024063,0.014915,0.018300
노출(분),-0.127894,1.000000,0.077447,0.072351,0.111478,0.144344,-0.125432,-0.031129,-0.007397,0.001736,...,0.007614,-0.073471,0.003855,0.017053,-0.009316,0.035914,0.010075,0.013889,0.029604,-0.029170
마더코드,-0.080073,0.077447,1.000000,0.978878,-0.214696,-0.029025,-0.081033,0.019849,-0.036389,0.012167,...,-0.272431,0.050732,0.007025,0.096604,-0.054523,0.043733,-0.112625,-0.025474,-0.008312,0.041540
상품코드,-0.095392,0.072351,0.978878,1.000000,-0.227098,-0.015692,-0.096014,0.015430,-0.036677,0.023000,...,-0.287225,0.057643,0.006295,0.101208,-0.046301,0.031806,-0.127481,-0.017509,-0.012325,0.034633
판매단가,-0.059455,0.111478,-0.214696,-0.227098,1.000000,-0.248520,-0.054958,-0.069088,0.070303,-0.380783,...,0.728397,-0.196290,-0.111164,-0.182507,-0.108437,0.000689,-0.071881,0.162619,-0.107470,-0.117543
취급액,0.077449,0.144344,-0.029025,-0.015692,-0.248520,1.000000,0.073841,0.038166,0.055360,0.770111,...,-0.156092,0.351700,-0.056086,0.071268,0.149999,-0.098988,-0.076373,0.039232,-0.057579,0.000752
월,0.995680,-0.125432,-0.081033,-0.096014,-0.054958,0.073841,1.000000,-0.000289,-0.019322,0.076983,...,-0.131632,0.035979,0.148201,-0.049911,0.071029,0.087817,0.028291,-0.023637,0.014718,0.017915
일,0.083051,-0.031129,0.019849,0.015430,-0.069088,0.038166,-0.000289,1.000000,0.010615,0.051452,...,-0.060315,0.022079,0.011844,0.013365,0.006573,0.013491,0.012822,-0.021572,0.015780,0.014191
요일,-0.018565,-0.007397,-0.036389,-0.036677,0.070303,0.055360,-0.019322,0.010615,1.000000,0.016060,...,0.084562,-0.036631,-0.005861,-0.014898,0.000507,-0.001830,-0.028290,-0.053252,0.024957,0.047904
수량,0.081024,0.001736,0.012167,0.023000,-0.380783,0.770111,0.076983,0.051452,0.016060,1.000000,...,-0.306462,0.543791,-0.084609,0.053188,0.226918,-0.048627,-0.046078,-0.033786,-0.000187,0.045128
의류,-0.034002,-0.075145,-0.025360,-0.010843,-0.154869,0.044982,-0.035282,0.024744,0.046921,0.073961,...,-0.165997,-0.123445,-0.104681,-0.124064,-0.068949,-0.123569,-0.048937,-0.525340,0.320181,0.404553
주방,-0.059352,0.099009,0.236522,0.236738,-0.199880,-0.061106,-0.060960,0.012608,-0.048229,-0.118811,...,-0.212167,-0.157779,-0.133797,-0.158571,-0.088126,-0.157938,-0.062548,0.135652,-0.089585,-0.098109
가구,0.000575,0.005729,-0.078610,-0.070264,0.140776,-0.145638,0.006032,-0.064243,-0.019255,-0.182273,...,-0.125588,-0.093394,-0.079199,-0.093863,-0.052165,-0.093488,-0.037024,0.080297,-0.053028,-0.058074
건강기능,0.031041,0.007822,0.039803,0.036446,-0.077285,0.026018,0.028114,0.037996,-0.015404,0.026009,...,-0.067298,-0.050047,-0.042440,-0.050298,-0.027953,-0.050097,-0.019840,0.043028,-0.028416,-0.031120
가전,-0.135176,0.007614,-0.272431,-0.287225,0.728397,-0.156092,-0.131632,-0.060315,0.084562,-0.306462,...,1.000000,-0.155962,-0.132256,-0.156745,-0.087111,-0.156119,-0.061828,0.134090,-0.088554,-0.096979
농수축,0.038659,-0.073471,0.050732,0.057643,-0.196290,0.351700,0.035979,0.022079,-0.036631,0.543791,...,-0.155962,1.000000,-0.098353,-0.116564,-0.064781,-0.116098,-0.045979,0.099717,-0.065853,-0.072119
생활용품,0.147118,0.003855,0.007025,0.006295,-0.111164,-0.056086,0.148201,0.011844,-0.005861,-0.084609,...,-0.132256,-0.098353,1.000000,-0.098847,-0.054934,-0.098452,-0.038990,0.084560,-0.055844,-0.061157
속옷,-0.049177,0.017053,0.096604,0.101208,-0.182507,0.071268,-0.049911,0.013365,-0.014898,0.053188,...,-0.156745,-0.116564,-0.098847,1.000000,-0.065106,-0.116681,-0.046210,0.019255,-0.007615,-0.018617
이미용,0.070785,-0.009316,-0.054523,-0.046301,-0.108437,0.149999,0.071029,0.006573,0.000507,0.226918,...,-0.087111,-0.064781,-0.054934,-0.065106,1.000000,-0.064846,-0.025681,0.055696,-0.036782,-0.040281
잡화,0.088895,0.035914,0.043733,0.031806,0.000689,-0.098988,0.087817,0.013491,-0.001830,-0.048627,...,-0.156119,-0.116098,-0.098452,-0.116681,-0.064846,1.000000,-0.046025,-0.115252,0.099063,0.062248
침구,0.030184,0.010075,-0.112625,-0.127481,-0.071881,-0.076373,0.028291,0.012822,-0.028290,-0.046078,...,-0.061828,-0.045979,-0.038990,-0.046210,-0.025681,-0.046025,1.000000,0.039531,-0.026106,-0.028590
무관,-0.024063,0.013889,-0.025474,-0.017509,0.162619,0.039232,-0.023637,-0.021572,-0.053252,-0.033786,...,0.134090,0.099717,0.084560,0.019255,0.055696,-0.115252,0.039531,1.000000,-0.660403,-0.723239
여성,0.014915,0.029604,-0.008312,-0.012325,-0.107470,-0.057579,0.014718,0.015780,0.024957,-0.000187,...,-0.088554,-0.065853,-0.055844,-0.007615,-0.036782,0.099063,-0.026106,-0.660403,1.000000,-0.040948
남성,0.018300,-0.029170,0.041540,0.034633,-0.117543,0.000752,0.017915,0.014191,0.047904,0.045128,...,-0.096979,-0.072119,-0.061157,-0.018617,-0.040281,0.062248,-0.028590,-0.723239,-0.040948,1.000000

In [231]:
mydata

,Unnamed: 0,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액,월,...,가전,농수축,생활용품,속옷,이미용,잡화,침구,무관,여성,남성
0,0,2019-01-01 6:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,2099000,1,...,0,0,0,0,0,0,0,0,0,1
1,1,2019-01-01 6:00,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900,4371000,1,...,0,0,0,0,0,0,0,0,1,0
2,2,2019-01-01 6:20,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,3262000,1,...,0,0,0,0,0,0,0,0,0,1
3,3,2019-01-01 6:20,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900,6955000,1,...,0,0,0,0,0,0,0,0,1,0
4,4,2019-01-01 6:40,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,6672000,1,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37367,38299,2019-12-31 23:40,NaN,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000,10157000,12,...,0,0,0,0,0,0,0,1,0,0
37368,38300,2020-01-01 0:00,20.0,100448,201383,무이자쿠첸압력밥솥 10인용,주방,178000,50929000,1,...,0,0,0,0,0,0,0,1,0,0
37369,38301,2020-01-01 0:00,NaN,100448,201390,일시불쿠첸압력밥솥 10인용,주방,168000,104392000,1,...,0,0,0,0,0,0,0,1,0,0
37370,38302,2020-01-01 0:00,NaN,100448,201384,무이자쿠첸압력밥솥 6인용,주방,158000,13765000,1,...,0,0,0,0,0,0,0,1,0,0
37371,38303,2020-01-01 0:00,NaN,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000,46608000,1,...,0,0,0,0,0,0,0,1,0,0

In [233]:
mydata['방송일시'].astype(float)

ValueError: could not convert string to float: '2019-01-01 6:00'

In [234]:
mydata['방송일시']= pd.to_datetime(mydata['방송일시'])

In [235]:
mydata

,Unnamed: 0,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액,월,...,가전,농수축,생활용품,속옷,이미용,잡화,침구,무관,여성,남성
0,0,2019-01-01 06:00:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,2099000,1,...,0,0,0,0,0,0,0,0,0,1
1,1,2019-01-01 06:00:00,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900,4371000,1,...,0,0,0,0,0,0,0,0,1,0
2,2,2019-01-01 06:20:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,3262000,1,...,0,0,0,0,0,0,0,0,0,1
3,3,2019-01-01 06:20:00,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900,6955000,1,...,0,0,0,0,0,0,0,0,1,0
4,4,2019-01-01 06:40:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,6672000,1,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37367,38299,2019-12-31 23:40:00,NaN,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000,10157000,12,...,0,0,0,0,0,0,0,1,0,0
37368,38300,2020-01-01 00:00:00,20.0,100448,201383,무이자쿠첸압력밥솥 10인용,주방,178000,50929000,1,...,0,0,0,0,0,0,0,1,0,0
37369,38301,2020-01-01 00:00:00,NaN,100448,201390,일시불쿠첸압력밥솥 10인용,주방,168000,104392000,1,...,0,0,0,0,0,0,0,1,0,0
37370,38302,2020-01-01 00:00:00,NaN,100448,201384,무이자쿠첸압력밥솥 6인용,주방,158000,13765000,1,...,0,0,0,0,0,0,0,1,0,0
37371,38303,2020-01-01 00:00:00,NaN,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000,46608000,1,...,0,0,0,0,0,0,0,1,0,0

In [237]:
mydata.corr()

,Unnamed: 0,노출(분),마더코드,상품코드,판매단가,취급액,월,일,요일,수량,...,가전,농수축,생활용품,속옷,이미용,잡화,침구,무관,여성,남성
Unnamed: 0,1.000000,-0.127894,-0.080073,-0.095392,-0.059455,0.077449,0.995680,0.083051,-0.018565,0.081024,...,-0.135176,0.038659,0.147118,-0.049177,0.070785,0.088895,0.030184,-0.024063,0.014915,0.018300
노출(분),-0.127894,1.000000,0.077447,0.072351,0.111478,0.144344,-0.125432,-0.031129,-0.007397,0.001736,...,0.007614,-0.073471,0.003855,0.017053,-0.009316,0.035914,0.010075,0.013889,0.029604,-0.029170
마더코드,-0.080073,0.077447,1.000000,0.978878,-0.214696,-0.029025,-0.081033,0.019849,-0.036389,0.012167,...,-0.272431,0.050732,0.007025,0.096604,-0.054523,0.043733,-0.112625,-0.025474,-0.008312,0.041540
상품코드,-0.095392,0.072351,0.978878,1.000000,-0.227098,-0.015692,-0.096014,0.015430,-0.036677,0.023000,...,-0.287225,0.057643,0.006295,0.101208,-0.046301,0.031806,-0.127481,-0.017509,-0.012325,0.034633
판매단가,-0.059455,0.111478,-0.214696,-0.227098,1.000000,-0.248520,-0.054958,-0.069088,0.070303,-0.380783,...,0.728397,-0.196290,-0.111164,-0.182507,-0.108437,0.000689,-0.071881,0.162619,-0.107470,-0.117543
취급액,0.077449,0.144344,-0.029025,-0.015692,-0.248520,1.000000,0.073841,0.038166,0.055360,0.770111,...,-0.156092,0.351700,-0.056086,0.071268,0.149999,-0.098988,-0.076373,0.039232,-0.057579,0.000752
월,0.995680,-0.125432,-0.081033,-0.096014,-0.054958,0.073841,1.000000,-0.000289,-0.019322,0.076983,...,-0.131632,0.035979,0.148201,-0.049911,0.071029,0.087817,0.028291,-0.023637,0.014718,0.017915
일,0.083051,-0.031129,0.019849,0.015430,-0.069088,0.038166,-0.000289,1.000000,0.010615,0.051452,...,-0.060315,0.022079,0.011844,0.013365,0.006573,0.013491,0.012822,-0.021572,0.015780,0.014191
요일,-0.018565,-0.007397,-0.036389,-0.036677,0.070303,0.055360,-0.019322,0.010615,1.000000,0.016060,...,0.084562,-0.036631,-0.005861,-0.014898,0.000507,-0.001830,-0.028290,-0.053252,0.024957,0.047904
수량,0.081024,0.001736,0.012167,0.023000,-0.380783,0.770111,0.076983,0.051452,0.016060,1.000000,...,-0.306462,0.543791,-0.084609,0.053188,0.226918,-0.048627,-0.046078,-0.033786,-0.000187,0.045128
의류,-0.034002,-0.075145,-0.025360,-0.010843,-0.154869,0.044982,-0.035282,0.024744,0.046921,0.073961,...,-0.165997,-0.123445,-0.104681,-0.124064,-0.068949,-0.123569,-0.048937,-0.525340,0.320181,0.404553
주방,-0.059352,0.099009,0.236522,0.236738,-0.199880,-0.061106,-0.060960,0.012608,-0.048229,-0.118811,...,-0.212167,-0.157779,-0.133797,-0.158571,-0.088126,-0.157938,-0.062548,0.135652,-0.089585,-0.098109
가구,0.000575,0.005729,-0.078610,-0.070264,0.140776,-0.145638,0.006032,-0.064243,-0.019255,-0.182273,...,-0.125588,-0.093394,-0.079199,-0.093863,-0.052165,-0.093488,-0.037024,0.080297,-0.053028,-0.058074
건강기능,0.031041,0.007822,0.039803,0.036446,-0.077285,0.026018,0.028114,0.037996,-0.015404,0.026009,...,-0.067298,-0.050047,-0.042440,-0.050298,-0.027953,-0.050097,-0.019840,0.043028,-0.028416,-0.031120
가전,-0.135176,0.007614,-0.272431,-0.287225,0.728397,-0.156092,-0.131632,-0.060315,0.084562,-0.306462,...,1.000000,-0.155962,-0.132256,-0.156745,-0.087111,-0.156119,-0.061828,0.134090,-0.088554,-0.096979
농수축,0.038659,-0.073471,0.050732,0.057643,-0.196290,0.351700,0.035979,0.022079,-0.036631,0.543791,...,-0.155962,1.000000,-0.098353,-0.116564,-0.064781,-0.116098,-0.045979,0.099717,-0.065853,-0.072119
생활용품,0.147118,0.003855,0.007025,0.006295,-0.111164,-0.056086,0.148201,0.011844,-0.005861,-0.084609,...,-0.132256,-0.098353,1.000000,-0.098847,-0.054934,-0.098452,-0.038990,0.084560,-0.055844,-0.061157
속옷,-0.049177,0.017053,0.096604,0.101208,-0.182507,0.071268,-0.049911,0.013365,-0.014898,0.053188,...,-0.156745,-0.116564,-0.098847,1.000000,-0.065106,-0.116681,-0.046210,0.019255,-0.007615,-0.018617
이미용,0.070785,-0.009316,-0.054523,-0.046301,-0.108437,0.149999,0.071029,0.006573,0.000507,0.226918,...,-0.087111,-0.064781,-0.054934,-0.065106,1.000000,-0.064846,-0.025681,0.055696,-0.036782,-0.040281
잡화,0.088895,0.035914,0.043733,0.031806,0.000689,-0.098988,0.087817,0.013491,-0.001830,-0.048627,...,-0.156119,-0.116098,-0.098452,-0.116681,-0.064846,1.000000,-0.046025,-0.115252,0.099063,0.062248
침구,0.030184,0.010075,-0.112625,-0.127481,-0.071881,-0.076373,0.028291,0.012822,-0.028290,-0.046078,...,-0.061828,-0.045979,-0.038990,-0.046210,-0.025681,-0.046025,1.000000,0.039531,-0.026106,-0.028590
무관,-0.024063,0.013889,-0.025474,-0.017509,0.162619,0.039232,-0.023637,-0.021572,-0.053252,-0.033786,...,0.134090,0.099717,0.084560,0.019255,0.055696,-0.115252,0.039531,1.000000,-0.660403,-0.723239
여성,0.014915,0.029604,-0.008312,-0.012325,-0.107470,-0.057579,0.014718,0.015780,0.024957,-0.000187,...,-0.088554,-0.065853,-0.055844,-0.007615,-0.036782,0.099063,-0.026106,-0.660403,1.000000,-0.040948
남성,0.018300,-0.029170,0.041540,0.034633,-0.117543,0.000752,0.017915,0.014191,0.047904,0.045128,...,-0.096979,-0.072119,-0.061157,-0.018617,-0.040281,0.062248,-0.028590,-0.723239,-0.040948,1.000000

In [240]:
mydata.to_csv('C:/Users/rmafu/Desktop/bigcon-master/mymy.csv')