In [8]:
import tensorflow as tf
import numpy as np
import matplotlib
import os
import matplotlib.pyplot as plt
import pandas as pd

In [9]:
data = pd.read_csv('mymy.csv')

In [10]:
seq_length = 7
data_dim = 4
hidden_dim = 10
output_dim = 1
learning_rate = 0.01
lteration = 500

In [14]:
data

,Unnamed: 0,Unnamed: 0.1,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액,...,가전,농수축,생활용품,속옷,이미용,잡화,침구,무관,여성,남성
0,0,0,2019-01-01 06:00:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,2099000,...,0,0,0,0,0,0,0,0,0,1
1,1,1,2019-01-01 06:00:00,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900,4371000,...,0,0,0,0,0,0,0,0,1,0
2,2,2,2019-01-01 06:20:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,3262000,...,0,0,0,0,0,0,0,0,0,1
3,3,3,2019-01-01 06:20:00,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900,6955000,...,0,0,0,0,0,0,0,0,1,0
4,4,4,2019-01-01 06:40:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,6672000,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37367,37367,38299,2019-12-31 23:40:00,NaN,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000,10157000,...,0,0,0,0,0,0,0,1,0,0
37368,37368,38300,2020-01-01 00:00:00,20.0,100448,201383,무이자쿠첸압력밥솥 10인용,주방,178000,50929000,...,0,0,0,0,0,0,0,1,0,0
37369,37369,38301,2020-01-01 00:00:00,NaN,100448,201390,일시불쿠첸압력밥솥 10인용,주방,168000,104392000,...,0,0,0,0,0,0,0,1,0,0
37370,37370,38302,2020-01-01 00:00:00,NaN,100448,201384,무이자쿠첸압력밥솥 6인용,주방,158000,13765000,...,0,0,0,0,0,0,0,1,0,0
37371,37371,38303,2020-01-01 00:00:00,NaN,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000,46608000,...,0,0,0,0,0,0,0,1,0,0